### ISSUE TITLE
development mode babel tries to require css files.

### ISSUE THREAD

**Issue by Alex-1989** [jaredpalmer/react-production-starter#242]
For production I have css files being imported correctly using ExtractTextPlugin, putting all my styles into a styles.css file which is referenced in the initial html the server returns. This works great!

The problem is that this approach does not work in development mode:

My webpack.client.dev.js looks like this:

```
const path = require('path')
const webpack = require('webpack')
const CONFIG = require('./webpack.base')
const ExtractTextPlugin = require('extract-text-webpack-plugin');

const { CLIENT_ENTRY, CLIENT_OUTPUT, PUBLIC_PATH } = CONFIG

module.exports = {
  devtool: 'eval',
  entry: {
    main: [
      'webpack/hot/only-dev-server',
      'webpack-hot-middleware/client',
      CLIENT_ENTRY
    ],
    vendor: [
      'react',
      'react-dom',
      'react-router',
      'redux',
      'react-redux',
      'aphrodite'
    ]
  },
  output: {
    filename: '[name].js',
    chunkFilename: '[name].chunk.js',
    publicPath: '/',
    path: CLIENT_OUTPUT
  },
  module: {
    preLoaders: [
      {
        // set up standard-loader as a preloader
        test: /\.jsx?$/,
        loader: 'standard',
        exclude: /(node_modules)/
      }
    ],
    loaders: [
      {
        test: /\.js$/,
        loader: 'babel',
        exclude: /(node_modules|server)/,
        query: {
          cacheDirectory: true,
          presets: ["es2015", "react", "stage-0"]
        }
      },
      { test: /\.css$/, loader: ExtractTextPlugin.extract("style-loader", "css-loader") }
    ]
  },
  standard: {
    // config options to be passed through to standard e.g.
    parser: 'babel-eslint'
  },
  plugins: [
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify('development'),
      '__DEV__': true
    }),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.optimize.CommonsChunkPlugin('vendor', 'vendor.js', 2),
    new webpack.NoErrorsPlugin(),
    new ExtractTextPlugin('styles.css', {
      allChunks: true
    }),
  ],
}
```

With this setup I get this error when I try and import a css file in a component:

```
.Select {
^
SyntaxError: Unexpected token .
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Alex/RPS_Static_Files/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

What are the options to resolve this without hacking require in development mode and telling it to ignore .css files (this results in markup warnings to do with a mismatch when ssr)?

**Comment by jaredpalmer** [comment]
Yeah this is an issue. You'd have to webpack the server or mess with `require`.

I suggest migrating your project over to my newer project [Razzle](https://github.com/jaredpalmer/razzle). It does this out of the box.

**Comment by Alex-1989** [comment]
Thanks for the quick response.

Any pointers for webpacking the server? Is there anything that can be reused from the current current webpack.client.dev.js?

**Comment by jaredpalmer** [comment]
checkout this branch: https://github.com/jaredpalmer/react-production-starter/tree/next

**Comment by Alex-1989** [comment]
Thanks for the link!

I've managed to update the project to webpack two and have the server building in development mode (which got rid of the css error.) I'm currently in the process of updating the rest of the webpack files and for the life of me cannot work out why vendors.js, main.js and style.js cannot be found when using hot reloading.

```
server 1 listening on port 5000
Hash: cfc5a3d8543a62f89919
Version: webpack 2.2.1
Time: 5635ms
     Asset     Size  Chunks                    Chunk Names
0.chunk.js  7.76 kB       0  [emitted]         
   main.js  1.37 MB       1  [emitted]  [big]  main
2.chunk.js  17.8 kB       2  [emitted]         
3.chunk.js  16.7 kB       3  [emitted]         
 vendor.js  3.64 MB       4  [emitted]  [big]  vendor
styles.css  11.9 kB       1  [emitted]         main
```

`    [1] multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server webpack-hot-middleware/client ./client 64 bytes {1} [built]`

```
const webpack = require('webpack');
const path = require('path');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const CONFIG = require('./webpack.base')
const { CLIENT_ENTRY, CLIENT_OUTPUT, PUBLIC_PATH } = CONFIG

module.exports = {
  devtool: 'inline-source-map',
    entry: {
    main: [
      'webpack/hot/only-dev-server',
      'webpack-hot-middleware/client',
      CLIENT_ENTRY
    ],
    vendor: [
      'react',
      'react-dom',
      'react-router',
      'redux',
      'react-redux',
      'aphrodite'
    ]
  },
  output: {
    filename: '[name].js',
    chunkFilename: '[name].chunk.js',
    publicPath: '/',
    path: CLIENT_OUTPUT
  },
  module: {
    rules: [
      {
        test: /\.(jpg|jpeg|png|gif|eot|ttf|woff|woff2)$/,
        loader: 'url-loader',
        options: {
          limit: 20000,
        },
      },
      {
        test: /\.js?$/,
        use: 'babel-loader',
        include: [
          path.join(__dirname, 'client'),
          path.join(__dirname, 'common'),
        ],
      },
      { test: /\.css$/, loader:     ExtractTextPlugin.extract({ fallback: 'style-loader', use: 'css-loader' }) },
      {
        test: /\.svg$/,
        loaders: [
          'babel-loader',
          {
            loader: 'react-svg-loader',
            query: {
              es5: false,
              jsx: true,
              svgo: {
                plugins: [{ removeTitle: false, removeStyleElement: true }],
                floatPrecision: 2,
              },
            },
          },
        ],
      },
    ],
  },
  plugins: [
    new ExtractTextPlugin({ filename: 'styles.css', disable: false, allChunks: true }),
    new webpack.NamedModulesPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoEmitOnErrorsPlugin(),
	  new webpack.optimize.CommonsChunkPlugin({ name: 'vendor', filename: 'vendor.js' }),
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify('development'),
      '__DEV__': true
    }),
  ],
}
```

```
                <script src="${ __PROD__ ? assets.vendor.js : '/vendor.js' }"></script>
                <script async src="${ __PROD__ ? assets.main.js : '/main.js' }" ></script>
                <link rel="stylesheet" type="text/css" href="${ __PROD__ ? assets.main.css : '/styles.css' }">

```
Does anything look out of the ordinary there ? I've confirmed  __PROD__ is false.

**Comment by jaredpalmer** [comment]
There is an issue with your `output.publicPath` pointing to the wrong place.  That's what I would play around with / read about. 

Just note the `next` branch uses `webpack-dev-server` and not `webpack-dev-middleware/webpack-hot-middleware` to serve client assets (js, css) on another port. Not sure if that's what part you copied.

**Comment by Alex-1989** [comment]
Great, thanks! Just got wp2 working in production so the final thing to solve now is the hmr for development mode.

**Comment by Alex-1989** [comment]
Did you manage to get HMR working for express? Are there any gotchas? 

```
Hash: 4d1d57bdba1cef05d754
Version: webpack 2.2.1
Time: 59ms
                               Asset      Size  Chunks             Chunk Names
                         0.server.js   3.21 kB       0  [emitted]  
                         1.server.js    6.3 kB       1  [emitted]  
                         2.server.js   6.04 kB       2  [emitted]  
                           server.js   72.9 kB       3  [emitted]  main
3.1fcdeab98973eda2318c.hot-update.js    5.2 kB       3  [emitted]  main
1fcdeab98973eda2318c.hot-update.json  43 bytes          [emitted]  
[./server/fakeDB.js] ./server/fakeDB.js 5.02 kB {3} [built]
    + 53 hidden modules
[HMR] Updated modules:
[HMR]  - ./server/fakeDB.js
[HMR]  - ./server/api/posts.js
[HMR]  - ./server/server.js
[HMR] Update applied.
```
It detects the change and states that its applied but the posts endpoint still returns the old data.

**Comment by jaredpalmer** [comment]
```
import express from 'express';
import app from './server';

if (module.hot) {
  module.hot.accept('./server', function() {
    console.log('🔁  HMR Reloading `./server`...');
  });
  console.info('✅  Server-side HMR Enabled!');
}

export default express()
  .use((req, res) => app.handle(req, res))
  .listen(process.env.PORT || 3000, function(err) {
    if (err) {
      console.error(err);
      return;
    }
    console.log(`> Started on 3000`);
  });
```
